### ISSUE TITLE
Compile error type mismatch?

### ISSUE THREAD

**Issue by axos88** [1wilkens/pam-auth#8]
```
#cargo build  --target arm-unknown-linux-gnueabi 
   Compiling users v0.5.3
   Compiling pam-sys v0.5.4
   Compiling pam-auth v0.5.3
error[E0308]: mismatched types
  --> /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/pam-auth-0.5.3/src/env.rs:56:46
   |
56 |         unsafe { pam::raw::pam_misc_drop_env(self.ptr as *mut *mut i8) };
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8
   |
   = note: expected type `*mut *mut u8`
              found type `*mut *mut i8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `pam-auth`.

```

**Comment by 1wilkens** [comment]
Hmm that's strange..
The env module in general is not very mature and probably buggy but should compile in any case. I just tried to compile pam-auth with the latest nightly and everything works as intended. Given that `cargo release` builds prior to uploading I am not sure what broke here.
What rust version are you using?

**Comment by 1wilkens** [comment]
I just realized that you are compiling for arm..
I didn't build the the library for arm myself but I assumed it would work. I think this breaks because arm has different definitions of `c_char` in `libc`? I am not sure how to handle this, as the `wrapped` module was supposed to use "native" types only instead of relying on c types. This could probably be solved with a conditional on the target architecture but I currently don't have the time to setup cross compiling myself.
In the meantime feel free to write a PR or wait until I can get to it (Full disclosure: which might be never =/)

**Comment by axos88** [comment]
Hmm, I would find it strange to have different definitions for c_char, although the C spec does not actually define if it should be signed or unsigned, so it's possible.

I will try to tinker around with this too, although I reverted to version 0.4.1 for now which seems to compile.
